### ISSUE TITLE
"Unbound module X" (Regression 1.5.2 -> 1.6.0)

### ISSUE THREAD

**Issue by cemerick** [jaredly/reason-language-server#287]
RLS v1.5.2 works well on my project: all OCaml 4.07, using dune 1.6.3; `dune runtest` is very comprehensive, and succeeds.

RLS 1.6.0 and 1.6.1 both fall down on all sources of my project that use a particular module, which happens to be called `Geom`. Note that tooltips and such are shown as expected within `Geom`, which seems interesting. I've `rm`'d `_build` as well as all autogenerated `.merlin` files in the project directories a number of times prior to running a build and restarting RLS, hoping that would knock things back to order, without success.

Upon opening an affected file, LSP logs this:

```
➡️ running bsc /home/chas/.opam/4.07.1+flambda/bin/ocamlopt.opt -c -I
'/home/chas/dev/pdfdata.io/pdfql/_build/default/test/.testgeom.objs/byte' -I
'/home/chas/dev/pdfdata.io/pdfql/_build/default/test/../src/.pdfql.objs/byte'
-I '/home/chas/.opam/4.07.1+flambda/lib/yojson' -I
'/home/chas/.opam/4.07.1+flambda/lib/xmlm' -I
'/home/chas/.opam/4.07.1+flambda/lib/uchar' -I
'/home/chas/.opam/4.07.1+flambda/lib/sequence' -I
'/home/chas/.opam/4.07.1+flambda/lib/seq' -I
'/home/chas/.opam/4.07.1+flambda/lib/result' -I
'/home/chas/.opam/4.07.1+flambda/lib/qcheck-ounit' -I
'/home/chas/.opam/4.07.1+flambda/lib/qcheck-core/runner' -I
'/home/chas/.opam/4.07.1+flambda/lib/qcheck-core' -I
'/home/chas/.opam/4.07.1+flambda/lib/qcheck' -I
'/home/chas/.opam/4.07.1+flambda/lib/ppx_deriving' -I
'/home/chas/.opam/4.07.1+flambda/lib/oseq' -I
'/home/chas/.opam/4.07.1+flambda/lib/ocaml/threads' -I
'/home/chas/.opam/4.07.1+flambda/lib/ocaml' -I
'/home/chas/.opam/4.07.1+flambda/lib/oUnit' -I
'/home/chas/.opam/4.07.1+flambda/lib/num' -I
'/home/chas/.opam/4.07.1+flambda/lib/gen' -I
'/home/chas/.opam/4.07.1+flambda/lib/ezxmlm' -I
'/home/chas/.opam/4.07.1+flambda/lib/easy-format' -I
'/home/chas/.opam/4.07.1+flambda/lib/containers/monomorphic' -I
'/home/chas/.opam/4.07.1+flambda/lib/containers/data' -I
'/home/chas/.opam/4.07.1+flambda/lib/containers' -I
'/home/chas/.opam/4.07.1+flambda/lib/bytes' -I
'/home/chas/.opam/4.07.1+flambda/lib/biniou' -I
'/home/chas/.opam/4.07.1+flambda/lib/bigstringaf' -I
'/home/chas/.opam/4.07.1+flambda/lib/batteries' -I
'/home/chas/.opam/4.07.1+flambda/lib/angstrom' -I
'/home/chas/.opam/4.07.1+flambda/lib/ocaml' -bin-annot -w
@a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats
-short-paths -keep-locs -warn-error -9-26-27-32-33-39 -w
@a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats
-short-paths -keep-locs -warn-error -9-26-27-32-33-39 -w
@a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats
-short-paths -keep-locs -warn-error -9-26-27-32-33-39 -ppx
'/home/chas/dev/pdfdata.io/pdfql/_build/default/.ppx/30a18adec0a1407675322d723bf1b0ae/ppx.exe
--as-ppx --cookie '\''library-name="testgeom"'\''' -impl
/home/chas/dev/pdfdata.io/pdfql/_build/.lsp/testgeom__Testgeom.ast with pwd
/home/chas/dev/pdfdata.io/pdfql/test
```

Running that particular command within the indicated pwd does indeed yield an `Unbound module Geom` error message.

I'm happy to try anything here (incl. install patched builds) to diagnose and confirm a fix, if needed.

**Comment by cemerick** [comment]
FWIW, this remains the case with the recently-released 1.7.0. 1.5.2 remains functional.

**Comment by cemerick** [comment]
After completely wiping the switch I was using and setting it up from scratch, I can't repro this. Closing.
